language: rust
cache: cargo
rust: nightly

matrix:
  # clear matrix
  exclude:
    - rust: nightly
  include:
    - env: TARGET=cortex-m3
      dist: trusty
      sudo: required
    - env: TARGET=cortex-m4f
      dist: trusty
      sudo: required
    - env: TARGET=no-linker-field
      dist: trusty
      sudo: required
    - env: TARGET=thumbv7m-none-eabi
      dist: trusty
      sudo: required
    - env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - sudo apt-get update

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

branches:
  only:
    - auto
    - try

notifications:
  email:
    on_success: never
  webhooks: http://homu.herokuapp.com/travis
